"""
AI Web Scraper - Configurações e Seletores
"""

import os
from pathlib import Path

# Diretórios
BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# User-Agent moderno para evitar bloqueios
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)

# Seletores do Google Maps (atualizados para a versão pt-BR)
SELECTORS = {
    # Lista de resultados
    "feed": "div[role='feed']",
    "result_item": "div[role='feed'] > div > div > a[href*='/maps/place/']",
    "result_container": "div[role='feed'] > div",
    
    # Detalhes do item
    "title": "h1.DUwDvf",
    "rating": "div.F7nice span[aria-hidden='true']",
    "reviews_count": "div.F7nice span[aria-label*='avaliações'], div.F7nice span[aria-label*='reviews']",
    "category": "button[jsaction*='pane.rating.category']",
    "address_btn": "button[data-item-id='address']",
    "website_btn": "a[data-item-id='authority']",
    "phone_btn": "button[data-item-id*='phone:tel:']",
    "hours_btn": "button[data-item-id*='oh:']",
}

# Configurações de Scraping
DEFAULT_MAX_RESULTS = 30
HEADLESS = True
BROWSER_TIMEOUT_MS = 25000
HTTP_TIMEOUT_SECONDS = 7.0

# Nichos padrão sugeridos para o mercado Fitness no Brasil
FITNESS_NICHES = [
    "Academia",
    "Studio de Pilates",
    "Box de CrossFit",
    "Studio de Treinamento Funcional",
    "Academia de Lutas / Muay Thai / Jiu-Jitsu",
    "Studio de Yoga",
    "Personal Trainer Studio",
    "Centro de Ginástica e Dança"
]

# Regiões, Capitais, Bairros Nobres e Cidades Polo do Brasil para o Modo Piloto Automático
BRAZIL_REGIONS = [
    # --- SÃO PAULO CAPITAL (Zonas Nobres & Alta Densidade) ---
    "Moema, São Paulo SP",
    "Pinheiros, São Paulo SP",
    "Jardins, São Paulo SP",
    "Itaim Bibi, São Paulo SP",
    "Vila Olímpia, São Paulo SP",
    "Vila Madalena, São Paulo SP",
    "Perdizes, São Paulo SP",
    "Higienópolis, São Paulo SP",
    "Vila Mariana, São Paulo SP",
    "Tatuapé, São Paulo SP",
    "Anália Franco, São Paulo SP",
    "Mooca, São Paulo SP",
    "Santana, São Paulo SP",
    "Tucuruvi, São Paulo SP",
    "Morumbi, São Paulo SP",
    "Santo Amaro, São Paulo SP",
    "Campo Belo, São Paulo SP",
    "Saúde, São Paulo SP",
    "Ipiranga, São Paulo SP",
    "Aclimação, São Paulo SP",
    "Barra Funda, São Paulo SP",
    "Lapa, São Paulo SP",
    "Butantã, São Paulo SP",
    "Bela Vista, São Paulo SP",
    "Consolação, São Paulo SP",
    "Casa Verde, São Paulo SP",

    # --- SÃO PAULO (Região Metropolitana & Interior) ---
    "Alphaville, Barueri SP",
    "Granja Viana, Cotia SP",
    "Cambuí, Campinas SP",
    "Taquaral, Campinas SP",
    "Nova Campinas, Campinas SP",
    "Barão Geraldo, Campinas SP",
    "Jardim Botânico, Ribeirão Preto SP",
    "Alto da Boa Vista, Ribeirão Preto SP",
    "Gonzaga, Santos SP",
    "Ponta da Praia, Santos SP",
    "Boqueirão, Santos SP",
    "Jardim Aquárius, São José dos Campos SP",
    "Vila Ema, São José dos Campos SP",
    "Urbanova, São José dos Campos SP",
    "Campolim, Sorocaba SP",
    "Jundiaí SP",
    "Piracicaba SP",
    "Bauru SP",
    "São José do Rio Preto SP",
    "Araraquara SP",
    "São Carlos SP",
    "Franca SP",
    "Americana SP",
    "Limeira SP",
    "Indaiatuba SP",
    "Valinhos SP",
    "Vinhedo SP",
    "Atibaia SP",
    "Bragança Paulista SP",
    "São Caetano do Sul SP",
    "Santo André SP",
    "São Bernardo do Campo SP",
    "Mogi das Cruzes SP",
    "Guarulhos SP",
    "Osasco SP",

    # --- RIO DE JANEIRO (Capital & Estado) ---
    "Barra da Tijuca, Rio de Janeiro RJ",
    "Recreio dos Bandeirantes, Rio de Janeiro RJ",
    "Copacabana, Rio de Janeiro RJ",
    "Ipanema, Rio de Janeiro RJ",
    "Leblon, Rio de Janeiro RJ",
    "Botafogo, Rio de Janeiro RJ",
    "Flamengo, Rio de Janeiro RJ",
    "Tijuca, Rio de Janeiro RJ",
    "Laranjeiras, Rio de Janeiro RJ",
    "Gávea, Rio de Janeiro RJ",
    "Jardim Botânico, Rio de Janeiro RJ",
    "Humaitá, Rio de Janeiro RJ",
    "São Conrado, Rio de Janeiro RJ",
    "Méier, Rio de Janeiro RJ",
    "Freguesia de Jacarepaguá, Rio de Janeiro RJ",
    "Taquara, Rio de Janeiro RJ",
    "Icaraí, Niterói RJ",
    "Camboinhas, Niterói RJ",
    "Ingá, Niterói RJ",
    "Piratininga, Niterói RJ",
    "Volta Redonda RJ",
    "Resende RJ",
    "Petrópolis RJ",
    "Teresópolis RJ",
    "Nova Friburgo RJ",
    "Macaé RJ",
    "Campos dos Goytacazes RJ",
    "Cabo Frio RJ",
    "Armação dos Búzios RJ",

    # --- MINAS GERAIS ---
    "Savassi, Belo Horizonte MG",
    "Lourdes, Belo Horizonte MG",
    "Belvedere, Belo Horizonte MG",
    "Funcionários, Belo Horizonte MG",
    "Sion, Belo Horizonte MG",
    "Anchieta, Belo Horizonte MG",
    "Santo Agostinho, Belo Horizonte MG",
    "Buritis, Belo Horizonte MG",
    "Gutierrez, Belo Horizonte MG",
    "Pampulha, Belo Horizonte MG",
    "Castelo, Belo Horizonte MG",
    "Vila da Serra, Nova Lima MG",
    "Alphaville Lagoa dos Ingleses, Nova Lima MG",
    "Santa Mônica, Uberlândia MG",
    "Granja Marileusa, Uberlândia MG",
    "Uberaba MG",
    "Juiz de Fora MG",
    "Montes Claros MG",
    "Ipatinga MG",
    "Governador Valadares MG",
    "Poços de Caldas MG",
    "Pouso Alegre MG",
    "Varginha MG",
    "Divinópolis MG",
    "Sete Lagoas MG",

    # --- PARANÁ ---
    "Batel, Curitiba PR",
    "Bigorrilho, Curitiba PR",
    "Ecoville, Curitiba PR",
    "Juvevê, Curitiba PR",
    "Cabral, Curitiba PR",
    "Água Verde, Curitiba PR",
    "Centro Cívico, Curitiba PR",
    "Mercês, Curitiba PR",
    "Gleba Palhano, Londrina PR",
    "Centro, Londrina PR",
    "Zona 1, Maringá PR",
    "Zona 3, Maringá PR",
    "Cascavel PR",
    "Foz do Iguaçu PR",
    "Ponta Grossa PR",
    "Guarapuava PR",
    "Toledo PR",
    "São José dos Pinhais PR",

    # --- SANTA CATARINA ---
    "Centro, Florianópolis SC",
    "Jurerê Internacional, Florianópolis SC",
    "Lagoa da Conceição, Florianópolis SC",
    "Agronômica, Florianópolis SC",
    "Córrego Grande, Florianópolis SC",
    "Campeche, Florianópolis SC",
    "Balneário Camboriú SC",
    "Praia Brava, Itajaí SC",
    "Centro, Itajaí SC",
    "América, Joinville SC",
    "Atiradores, Joinville SC",
    "Vila Nova, Blumenau SC",
    "Victor Konder, Blumenau SC",
    "Criciúma SC",
    "Chapecó SC",
    "Tubarão SC",
    "Brusque SC",
    "Jaraguá do Sul SC",
    "Palhoça SC",
    "São José SC",

    # --- RIO GRANDE DO SUL ---
    "Moinhos de Vento, Porto Alegre RS",
    "Bela Vista, Porto Alegre RS",
    "Petrópolis, Porto Alegre RS",
    "Menino Deus, Porto Alegre RS",
    "Três Figueiras, Porto Alegre RS",
    "Mont'Serrat, Porto Alegre RS",
    "Rio Branco, Porto Alegre RS",
    "Praia de Belas, Porto Alegre RS",
    "Caxias do Sul RS",
    "Pelotas RS",
    "Canoas RS",
    "Santa Maria RS",
    "Passo Fundo RS",
    "Novo Hamburgo RS",
    "São Leopoldo RS",
    "Bento Gonçalves RS",
    "Gramado RS",

    # --- DISTRITO FEDERAL & GOIÁS ---
    "Asa Sul, Brasília DF",
    "Asa Norte, Brasília DF",
    "Sudoeste, Brasília DF",
    "Noroeste, Brasília DF",
    "Lago Sul, Brasília DF",
    "Lago Norte, Brasília DF",
    "Águas Claras, Brasília DF",
    "Guará, Brasília DF",
    "Taguatinga, Brasília DF",
    "Setor Bueno, Goiânia GO",
    "Setor Marista, Goiânia GO",
    "Jardim Goiás, Goiânia GO",
    "Setor Oeste, Goiânia GO",
    "Setor Sul, Goiânia GO",
    "Anápolis GO",
    "Rio Verde GO",
    "Aparecida de Goiânia GO",

    # --- CENTRO-OESTE (MT & MS) ---
    "Goiabeiras, Cuiabá MT",
    "Jardim das Américas, Cuiabá MT",
    "Santa Rosa, Cuiabá MT",
    "Várzea Grande MT",
    "Rondonópolis MT",
    "Sinop MT",
    "Chácara Cachoeira, Campo Grande MS",
    "Santa Fé, Campo Grande MS",
    "Jardim dos Estados, Campo Grande MS",
    "Dourados MS",

    # --- BAHIA & NORDESTE ---
    "Pituba, Salvador BA",
    "Barra, Salvador BA",
    "Itaigara, Salvador BA",
    "Caminho das Árvores, Salvador BA",
    "Graça, Salvador BA",
    "Ondina, Salvador BA",
    "Horto Florestal, Salvador BA",
    "Vil权力as do Atlântico, Lauro de Freitas BA",
    "Feira de Santana BA",
    "Vitória da Conquista BA",
    "Aldeota, Fortaleza CE",
    "Meireles, Fortaleza CE",
    "Cocó, Fortaleza CE",
    "Varjota, Fortaleza CE",
    "Guararapes, Fortaleza CE",
    "Dionísio Torres, Fortaleza CE",
    "Boa Viagem, Recife PE",
    "Parnamirim, Recife PE",
    "Graças, Recife PE",
    "Jaqueira, Recife PE",
    "Casa Forte, Recife PE",
    "Espinheiro, Recife PE",
    "Ponta Verde, Maceió AL",
    "Jatiúca, Maceió AL",
    "Pajuçara, Maceió AL",
    "Tirol, Natal RN",
    "Petrópolis, Natal RN",
    "Ponta Negra, Natal RN",
    "Manaíra, João Pessoa PB",
    "Tambaú, João Pessoa PB",
    "Cabo Branco, João Pessoa PB",
    "Bessa, João Pessoa PB",
    "Altiplano, João Pessoa PB",
    "Campina Grande PB",
    "13 de Julho, Aracaju SE",
    "Jardins, Aracaju SE",
    "Jóquei, Teresina PI",
    "Fátima, Teresina PI",
    "Ponta d'Areia, São Luís MA",
    "Renascença, São Luís MA",
    "Calhau, São Luís MA",

    # --- ESPÍRITO SANTO & NORTE ---
    "Praia do Canto, Vitória ES",
    "Jardim da Penha, Vitória ES",
    "Mata da Praia, Vitória ES",
    "Praia da Costa, Vila Velha ES",
    "Itapuã, Vila Velha ES",
    "Itaparica, Vila Velha ES",
    "Adrianópolis, Manaus AM",
    "Ponta Negra, Manaus AM",
    "Vieiralves, Manaus AM",
    "Nazaré, Belém PA",
    "Umarizal, Belém PA",
    "Batista Campos, Belém PA",
    "Graciosa, Palmas TO"
]
